# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='labels',
            field=models.CharField(choices=[('help_wanted', 'Help Wanted'), ('idea', 'Idea'), ('something_interesting', 'Something Interesting')], default='Help Wanted', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='attachment',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
