# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='labels',
            field=models.CharField(choices=[('help_wanted', 'Help Wanted'), ('idea', 'Idea'), ('something_interesting', 'Something Interesting')], max_length=50),
        ),
    ]
