# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(choices=[('entc', 'Electronics and Telecommunication'), ('comp', 'Computer Engineering'), ('it', 'Information Technology'), ('mech', 'Mechanical'), ('civil', 'Civil'), ('applied', 'Applied Science'), ('Management', 'Management')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.CharField(choices=[('mit', 'MIT'), ('mmcoe', 'MMCOE'), ('coep', 'COEP'), ('mit-adt', 'MIT-ADT')], max_length=20),
        ),
    ]
